version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk-buster
    working_directory: ~/app
    steps:
      - checkout

      # Install Maven 3.9.1
      - run:
          name: Install Maven 3.9.1
          command: |
            wget https://archive.apache.org/dist/maven/maven-3/3.9.1/binaries/apache-maven-3.9.1-bin.tar.gz
            tar -xvzf apache-maven-3.9.1-bin.tar.gz
            sudo mv apache-maven-3.9.1 /opt
            sudo ln -s /opt/apache-maven-3.9.1/bin/mvn /usr/bin/mvn

      # Build the JAR file
      - run:
          name: Build JAR file
          command: mvn -B -DskipTests clean package

      # Push Docker image to ECR
      - run:
          name: Push Docker image to ECR
          command: |
            docker build -t springtest .
            docker run --rm \
              -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
              -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
              -e AWS_DEFAULT_REGION=$AWS_REGION \
              -e ECR_REGISTRY=public.ecr.aws/j4y7c7s3 \
              -v $PWD:/app \
              circleci/aws-ecr:latest \
              sh -c 'docker login -u AWS -p $AWS_ACCESS_TOKEN $ECR_REGISTRY && docker tag springtest:latest $ECR_REGISTRY/springtest:latest && docker push $ECR_REGISTRY/springtest:latest'

workflows:
  build-and-push:
    jobs:
      - build:
          filters:
            branches:
              only: stagging
