version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk-buster
    working_directory: ~/app
    steps:
      - checkout

      # Install Maven 3.9.1
      - run:
          name: Install Maven 3.9.1
          command: |
            wget https://archive.apache.org/dist/maven/maven-3/3.9.1/binaries/apache-maven-3.9.1-bin.tar.gz
            tar -xvzf apache-maven-3.9.1-bin.tar.gz
            sudo mv apache-maven-3.9.1 /opt
            sudo ln -s /opt/apache-maven-3.9.1/bin/mvn /usr/bin/mvn

      # Install AWS CLI
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      # Build the JAR file
      - run:
          name: Build JAR file
          command: mvn -B -DskipTests clean package

      # Build and push the Docker image to ECR
      - run:
          name: Build and push Docker image to ECR
          command: |
            docker build -t springtest .
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/j4y7c7s3
            docker push public.ecr.aws/j4y7c7s3/springtest:latest

workflows:
  build-and-push:
    jobs:
      - build:
          filters:
            branches:
              only: stagging
