version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk-buster
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Maven 3.8.3
          command: |
            wget https://archive.apache.org/dist/maven/maven-3/3.8.3/binaries/apache-maven-3.8.3-bin.tar.gz
            tar -xzf apache-maven-3.8.3-bin.tar.gz
            sudo mv apache-maven-3.8.3 /opt/
            sudo ln -s /opt/apache-maven-3.8.3/bin/mvn /usr/local/bin/mvn
      - run:
          name: Build JAR file
          command: |
            mvn -B -DskipTests clean package

  deploy:
    docker:
      - image: amazon/aws-cli:latest
    steps:
      - run:
          name: Deploy to Elastic Beanstalk
          command: |
             aws configure set region eu-west-1
             aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
             aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
             s3key=Springtest-env-${CIRCLE_SHA1}.zip
             aws s3 sync target/*.jar s3://springo-bucket-env/${s3key}
             aws elasticbeanstalk update-environment --environment-name Springtest-env --version-label v${CIRCLE_BUILD_NUM} --source-bundle S3Bucket=springo-bucket-env,S3Key=${s3key}


workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: stagging
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: stagging