version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk-buster
        environment:
          DOCKER_HOST: tcp://localhost:2375
    working_directory: ~/app
    steps:
      - checkout

      # Install Maven 3.9.1
      - run:
          name: Install Maven 3.9.1
          command: |
            wget https://archive.apache.org/dist/maven/maven-3/3.9.1/binaries/apache-maven-3.9.1-bin.tar.gz
            tar -xvzf apache-maven-3.9.1-bin.tar.gz
            sudo mv apache-maven-3.9.1 /opt
            sudo ln -s /opt/apache-maven-3.9.1/bin/mvn /usr/bin/mvn

      # Build the JAR file
      - run:
          name: Build JAR file
          command: mvn -B -DskipTests clean package

      # Push Docker image to ECR
      - aws-ecr/push-image:
          region: us-east-1
          public-registry: true 
          public-registry-alias: j4y7c7s3 
          repo: springtest 

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only: stagging
