version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-cli: circleci/aws-cli@3.1.5

jobs:
  build-and-push:
    docker:
      - image: circleci/openjdk:17-jdk-buster
        environment:
          DOCKER_HOST: tcp://localhost:2375
    working_directory: ~/app
    steps:
      - checkout

      # Install Maven 3.9.1
      - run:
          name: Install Maven 3.9.1
          command: |
            wget https://archive.apache.org/dist/maven/maven-3/3.9.1/binaries/apache-maven-3.9.1-bin.tar.gz
            tar -xvzf apache-maven-3.9.1-bin.tar.gz
            sudo mv apache-maven-3.9.1 /opt
            sudo ln -s /opt/apache-maven-3.9.1/bin/mvn /usr/bin/mvn

      # Build the JAR file
      - run:
          name: Build JAR file
          command: mvn -B -DskipTests clean package

      # Authenticate and log in to ECR Public
      - aws-ecr/ecr-login-public:
          region: us-east-1

      # Push Docker image to ECR
      - aws-ecr/ecr-public-push-image:
          region: us-east-1
          repository-url: public.ecr.aws/j4y7c7s3/springtest
          image-tag: latest
          dockerfile: Dockerfile
          context: .

workflows:
  build-and-push:
    jobs:
      - build:
          filters:
            branches:
              only: stagging
