version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk-buster
        environment:
          DOCKER_HOST: tcp://localhost:2375
    working_directory: ~/app
    steps:
      - checkout

      # Install Maven 3.9.1
      - run:
          name: Install Maven 3.9.1
          command: |
            wget https://archive.apache.org/dist/maven/maven-3/3.9.1/binaries/apache-maven-3.9.1-bin.tar.gz
            tar -xvzf apache-maven-3.9.1-bin.tar.gz
            sudo mv apache-maven-3.9.1 /opt
            sudo ln -s /opt/apache-maven-3.9.1/bin/mvn /usr/bin/mvn

      # Build the JAR file
      - run:
          name: Build JAR file
          command: mvn -B -DskipTests clean package

      # Authenticate and log in to ECR Public
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY
          aws-region: REGION
      - run:
          name: Log in to ECR Public
          command: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      # Push Docker image to ECR
      - run:
          name: Build and push Docker image to ECR
          command: |
            docker build -t springtest .
            docker tag springtest:latest public.ecr.aws/j4y7c7s3/springtest:latest
            docker push public.ecr.aws/j4y7c7s3/springtest:latest

workflows:
  build-and-push:
    jobs:
      - build:
          filters:
            branches:
              only: staging
