# create circle ci config file to build and push file target/*.jar to S3 the updates jar file to AWS elastic beanstalk 
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk-buster
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Maven 3.8.3
          command: |
            wget https://archive.apache.org/dist/maven/maven-3/3.9.1/binaries/apache-maven-3.9.1-bin.tar.gz
            tar  -xvzf apache-maven-3.9.1-bin.tar.gz
            sudo  mv apache-maven-3.9.1 /opt
            sudo  ln -s /opt/apache-maven-3.9.1/bin/mvn /usr/bin/mvn
      - run: mvn -B -DskipTests clean package

  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: target/
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Upload file to S3
          command: aws s3 sync target/*.jar s3://spring-env-app-bucket
      

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: stagging
      - deploy_project:
          requires:
            - build
          filters:
            branches:
              only: stagging